Repository Team-Tokkit/Tokkit-Server, pull requests merged in 2025-05, with the labels that each got.

#29 ✨ Feat/#23 kakao map 주변 가맹점 조회 API 구현
  src/main/java/com/example/Tokkit_server/global/apiPayload/ApiResponse.java
  src/main/java/com/example/Tokkit_server/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/Tokkit_server/store/controller/StoreController.java
  src/main/java/com/example/Tokkit_server/store/dto/response/KakaoMapSearchResponse.java
  src/main/java/com/example/Tokkit_server/store/entity/Store.java
  src/main/java/com/example/Tokkit_server/store/enums/StoreCategory.java
  src/main/java/com/example/Tokkit_server/store/repository/StoreRepository.java
  src/main/java/com/example/Tokkit_server/store/service/StoreService.java
  src/main/java/com/example/Tokkit_server/store/service/command/StoreCommandService.java
  src/main/java/com/example/Tokkit_server/store/service/command/StoreCommandServiceImpl.java
  src/main/java/com/example/Tokkit_server/voucher/dto/request/VoucherSearchRequest.java
  src/main/java/com/example/Tokkit_server/voucher/repository/VoucherCustomRepositoryImpl.java
  src/main/java/com/example/Tokkit_server/voucher_ownership/entity/VoucherOwnership.java
  src/main/java/com/example/Tokkit_server/voucher_ownership/repository/VoucherOwnershipRepositoryImpl.java
  src/main/resources/sql/data.sql
  src/test/java/com/example/Tokkit_server/StoreCommandServiceTest.java
Labels: FEAT

#34 ♻️ Refactor/#34 Update CI/CD
  .github/workflows/deploy.yml
Labels: REFACTOR

#37 feat : 결제쪽 도메인 Redis 멱등키 기반 중복결제 방지 구현
  build.gradle
  src/main/java/com/example/Tokkit_server/email_validation/entity/EmailValidation.java
  src/main/java/com/example/Tokkit_server/email_validation/enums/EmailPurpose.java
  src/main/java/com/example/Tokkit_server/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/Tokkit_server/global/config/RedisConfig.java
  src/main/java/com/example/Tokkit_server/global/util/IdempotencyManager.java
  src/main/java/com/example/Tokkit_server/store/enums/StoreCategory.java
  src/main/java/com/example/Tokkit_server/transaction/enums/TransactionType.java
  src/main/java/com/example/Tokkit_server/voucher/dto/response/VoucherDetailResponse.java
  src/main/java/com/example/Tokkit_server/voucher_ownership/controller/VoucherOwnershipController.java
  src/main/java/com/example/Tokkit_server/voucher_ownership/dto/request/VoucherPaymentRequest.java
  src/main/java/com/example/Tokkit_server/voucher_ownership/repository/VoucherOwnershipRepositoryImpl.java
  src/main/java/com/example/Tokkit_server/wallet/controller/WalletController.java
  src/main/java/com/example/Tokkit_server/wallet/dto/request/VoucherPurchaseRequest.java
  src/main/java/com/example/Tokkit_server/wallet/dto/response/VoucherPurchaseResponse.java
  src/main/java/com/example/Tokkit_server/wallet/service/command/WalletCommandService.java
  src/main/java/com/example/Tokkit_server/wallet/service/query/WalletQueryService.java
  src/main/resources/application.yml
Labels: FEAT

#43 Feat/#42 시/도,시/군/구 API 구현 완료
  .gitignore
  src/main/java/com/example/Tokkit_server/email_validation/entity/EmailValidation.java
  src/main/java/com/example/Tokkit_server/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/Tokkit_server/region/controller/RegionController.java
  src/main/java/com/example/Tokkit_server/region/dto/response/SidoResponse.java
  src/main/java/com/example/Tokkit_server/region/dto/response/SigunguResponse.java
  src/main/java/com/example/Tokkit_server/region/entity/Region.java
  src/main/java/com/example/Tokkit_server/region/repository/RegionRepository.java
  src/main/java/com/example/Tokkit_server/region/service/command/RegionCommandService.java
  src/main/java/com/example/Tokkit_server/region/service/command/RegionCommandServiceImpl.java
Labels: FEAT

#30 Refactor/#28 바우처 응답 DTO 수정
  src/main/java/com/example/Tokkit_server/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/Tokkit_server/voucher_ownership/controller/VoucherOwnershipController.java
  src/main/java/com/example/Tokkit_server/voucher_ownership/entity/VoucherOwnership.java
  src/main/java/com/example/Tokkit_server/voucher_ownership/enums/VoucherOwnershipStatus.java
  src/main/java/com/example/Tokkit_server/voucher_ownership/repository/VoucherOwnershipRepositoryImpl.java
  src/main/java/com/example/Tokkit_server/voucher_ownership/service/VoucherOwnershipService.java
Labels: REFACTOR

#47 Refactor: controller단 filter 적용
  src/main/java/com/example/Tokkit_server/global/config/SecurityConfig.java
  src/main/java/com/example/Tokkit_server/store/controller/StoreController.java
  src/main/java/com/example/Tokkit_server/store/service/StoreService.java
  src/main/java/com/example/Tokkit_server/store/service/command/StoreCommandService.java
  src/main/java/com/example/Tokkit_server/store/service/command/StoreCommandServiceImpl.java
  src/main/java/com/example/Tokkit_server/voucher_ownership/controller/VoucherOwnershipController.java
  src/main/java/com/example/Tokkit_server/wallet/controller/WalletController.java
Labels: REFACTOR, SECURITY

#48 refactor: 간편 비밀번호 수정 로직 변경
  src/main/java/com/example/Tokkit_server/global/config/SecurityConfig.java
  src/main/java/com/example/Tokkit_server/user/entity/User.java
  src/main/java/com/example/Tokkit_server/user/service/UserService.java
Labels: REFACTOR

#50 Refactor: TransactioHistoryResponse에 id 추가
  src/main/java/com/example/Tokkit_server/wallet/dto/response/TransactionHistoryResponse.java
  src/main/java/com/example/Tokkit_server/wallet/service/command/WalletCommandService.java
  src/main/java/com/example/Tokkit_server/wallet/service/query/WalletQueryService.java
Labels: REFACTOR

#52 refactor : 잔액조회 응답 DTO 수정
  src/main/java/com/example/Tokkit_server/wallet/dto/response/WalletBalanceResponse.java
  src/main/java/com/example/Tokkit_server/wallet/service/command/WalletCommandService.java
Labels: REFACTOR

#53 Refactor: 유저 전자지갑 정보 조회 부분 삭제
  src/main/java/com/example/Tokkit_server/user/controller/UserController.java
  src/main/java/com/example/Tokkit_server/user/dto/response/UserWalletResponseDto.java
  src/main/java/com/example/Tokkit_server/user/service/UserService.java
Labels: REFACTOR

#56 Feat/#49 logging
  build.gradle
  src/main/java/com/example/Tokkit_server/api_request_log/entity/ApiRequestLog.java
  src/main/java/com/example/Tokkit_server/api_request_log/enums/Event.java
  src/main/java/com/example/Tokkit_server/api_request_log/filter/ApiLoggingFilter.java
  src/main/java/com/example/Tokkit_server/api_request_log/repository/ApiRequestLogRepository.java
  src/main/java/com/example/Tokkit_server/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/Tokkit_server/global/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/example/Tokkit_server/global/config/SecurityConfig.java
  src/main/java/com/example/Tokkit_server/global/filter/TraceIdFilter.java
  src/main/java/com/example/Tokkit_server/global/util/IdempotencyManager.java
  src/main/java/com/example/Tokkit_server/global/util/LoggingUtils.java
  src/main/java/com/example/Tokkit_server/login_log/entity/LoginLog.java
  src/main/java/com/example/Tokkit_server/login_log/filter/LogoutLoggingFilter.java
  src/main/java/com/example/Tokkit_server/login_log/listener/LoginLogListener.java
  src/main/java/com/example/Tokkit_server/login_log/repository/LoginLogRepository.java
  src/main/java/com/example/Tokkit_server/merchant/auth/CustomMerchantDetails.java
  src/main/java/com/example/Tokkit_server/merchant/auth/CustomMerchantDetailsService.java
  src/main/java/com/example/Tokkit_server/merchant/controller/MerchantController.java
  src/main/java/com/example/Tokkit_server/merchant/filter/CustomMerchantLoginFilter.java
  src/main/java/com/example/Tokkit_server/merchant/service/MerchantEmailService.java
  src/main/java/com/example/Tokkit_server/notice/service/query/NoticeQueryService.java
  src/main/java/com/example/Tokkit_server/notification/service/EmailNotificationService.java
  src/main/java/com/example/Tokkit_server/notification/service/NotificationServiceImpl.java
  src/main/java/com/example/Tokkit_server/ocr/service/BusinessOcrService.java
  src/main/java/com/example/Tokkit_server/ocr/service/IdCardOcrService.java
  src/main/java/com/example/Tokkit_server/ocr/service/KakaoAddressSearchService.java
  src/main/java/com/example/Tokkit_server/system_error_log/entity/SystemErrorLog.java
  src/main/java/com/example/Tokkit_server/system_error_log/enums/Severity.java
  src/main/java/com/example/Tokkit_server/system_error_log/repository/SystemErrorLogRepository.java
  src/main/java/com/example/Tokkit_server/system_error_log/service/SystemErrorLogService.java
  src/main/java/com/example/Tokkit_server/transaction/entity/Transaction.java
  src/main/java/com/example/Tokkit_server/transaction/enums/TransactionStatus.java
  src/main/java/com/example/Tokkit_server/transaction/service/query/TransactionLogService.java
  src/main/java/com/example/Tokkit_server/user/auth/CustomUserDetailsService.java
  src/main/java/com/example/Tokkit_server/user/controller/AuthController.java
  src/main/java/com/example/Tokkit_server/user/filter/CustomLoginFilter.java
  src/main/java/com/example/Tokkit_server/user/filter/JwtAuthenticationFilter.java
  src/main/java/com/example/Tokkit_server/user/service/AuthService.java
  src/main/java/com/example/Tokkit_server/user/service/EmailService.java
  src/main/java/com/example/Tokkit_server/user/utils/JwtUtil.java
  src/main/java/com/example/Tokkit_server/voucher_ownership/dto/request/VoucherPaymentRequest.java
  src/main/java/com/example/Tokkit_server/wallet/controller/WalletController.java
  src/main/java/com/example/Tokkit_server/wallet/dto/request/DepositToTokenRequest.java
  src/main/java/com/example/Tokkit_server/wallet/dto/request/DirectPaymentRequest.java
  src/main/java/com/example/Tokkit_server/wallet/dto/request/PasswordVerifyRequest.java
  src/main/java/com/example/Tokkit_server/wallet/dto/request/PaymentRequest.java
  src/main/java/com/example/Tokkit_server/wallet/dto/request/TokenToDepositRequest.java
  src/main/java/com/example/Tokkit_server/wallet/dto/request/VoucherPurchaseRequest.java
  src/main/java/com/example/Tokkit_server/wallet/service/WalletAuthService.java
  src/main/java/com/example/Tokkit_server/wallet/service/command/WalletCommandService.java
  src/main/java/com/example/Tokkit_server/wallet/service/query/WalletQueryService.java
  src/main/resources/logback-spring.xml
Labels: FEAT

#61 Fix/#60 log uri normalize
  src/main/java/com/example/Tokkit_server/api_request_log/filter/ApiLoggingFilter.java
  src/main/java/com/example/Tokkit_server/api_request_log/interceptor/ApiLoggingInterceptor.java
  src/main/java/com/example/Tokkit_server/global/config/SecurityConfig.java
  src/main/java/com/example/Tokkit_server/global/config/WebMvcConfig.java
  src/main/java/com/example/Tokkit_server/global/util/LoggingUtils.java
Labels: FIX

#62 refactor: createMerchantDtoResponse에 accountNumber 추가
  src/main/java/com/example/Tokkit_server/global/config/SecurityConfig.java
  src/main/java/com/example/Tokkit_server/merchant/dto/response/MerchantRegisterResponseDto.java
Labels: REFACTOR

#65 feat: Merchant 지갑 관련 기능 구현
  src/main/java/com/example/Tokkit_server/merchant/entity/Merchant.java
  src/main/java/com/example/Tokkit_server/store/dto/response/StoreInfoResponse.java
  src/main/java/com/example/Tokkit_server/store/service/StoreService.java
  src/main/java/com/example/Tokkit_server/wallet/controller/MerchantWalletController.java
  src/main/java/com/example/Tokkit_server/wallet/controller/WalletController.java
  src/main/java/com/example/Tokkit_server/wallet/service/command/MerchantWalletCommandService.java
  src/main/java/com/example/Tokkit_server/wallet/service/query/MerchantWalletQueryService.java
Labels: FEAT

#69 fix: jwt 인증 필터 충돌 에러 해결
  src/main/java/com/example/Tokkit_server/global/config/SecurityConfig.java
  src/main/java/com/example/Tokkit_server/merchant/filter/MerchantJwtAuthenticationFilter.java
  src/main/java/com/example/Tokkit_server/notice/controller/NoticeController.java
  src/main/java/com/example/Tokkit_server/notification/controller/NotificationController.java
  src/main/java/com/example/Tokkit_server/notification/controller/NotificationSettingController.java
  src/main/java/com/example/Tokkit_server/store/controller/StoreController.java
  src/main/java/com/example/Tokkit_server/user/filter/JwtAuthenticationFilter.java
  src/main/java/com/example/Tokkit_server/voucher/controller/VoucherController.java
  src/main/java/com/example/Tokkit_server/voucher_ownership/controller/VoucherOwnershipController.java
  src/main/java/com/example/Tokkit_server/wallet/controller/MerchantWalletController.java
  src/main/java/com/example/Tokkit_server/wallet/controller/WalletController.java
  src/main/java/com/example/Tokkit_server/wallet/dto/response/MerchantWalletBalanceResponse.java
  src/main/java/com/example/Tokkit_server/wallet/service/command/MerchantWalletCommandService.java
Labels: FIX

#70 Feat : 가맹점주의 바우처 목록 조회 및 검색 api 구현
  src/main/java/com/example/Tokkit_server/merchant/controller/MerchantVoucherController.java
  src/main/java/com/example/Tokkit_server/merchant/service/MerchantVoucherService.java
  src/main/java/com/example/Tokkit_server/voucher/repository/VoucherRepository.java
Labels: FEAT

#72 feat: 가맹점주 일일 매출 조회 api 구현
  src/main/java/com/example/Tokkit_server/transaction/repository/TransactionRepository.java
  src/main/java/com/example/Tokkit_server/wallet/controller/MerchantWalletController.java
  src/main/java/com/example/Tokkit_server/wallet/dto/response/MerchantDailyIncomeResponse.java
  src/main/java/com/example/Tokkit_server/wallet/service/command/MerchantWalletCommandService.java
Labels: FEAT

#109 :recycle: Refactor: Cors Filter 수정
  src/main/java/com/example/Tokkit_server/global/config/CorsConfig.java
Labels: SECURITY

#114 fix: HikariCP Pool size error
  src/main/java/com/example/Tokkit_server/TokkitServerApplication.java
  src/main/java/com/example/Tokkit_server/notification/service/NotificationServiceImpl.java
Labels: FIX
